inherits: ../deterministic.yaml
run_name: spatial_image_base_seed10
seed: 10
model:
  use_coordinates: true
  use_spatial_attention: true
  use_within_refiner: false
  use_between_refiner: false
training:
  max_hours: 8
